version: '2'
services: 
  wiremock:
    image: wiremock
    ports:
      - "7070:7070"
    cpu_shares: 4096

  ratpack:
    image: ratpack-app
    ports:
      - "5050:5050"
    links:
      - wiremock
    cpu_shares: 1024

  dropwizard:
    image: dropwizard-app
    ports:
      - "8080:8080"
    links:
      - wiremock
    cpu_shares: 1024
